SELECT a.PROMOTIONPLANNAME,a.MONTHFEE,d.AMOUNT AS DEDUCTFEE,a.PRORATE,B.LIMIT AS PROMOTIONLIMIT,c.CURRENTLIMIT AS LIMITFORCUSTOMER FROM rm_promotionplan a, RM_PROMOTIONPLAN_DETAIL b,
CRM_CUSTOMERS_PROMOTION c, CRM_CUSTOMERS_EXTRAUSAGE d
WHERE a.PROMOTIONPLANID=b.PROMOTIONPLANID AND c.PROMOTIONPLANDETAILID=b.PROMOTIONPLANDETAILID
AND a.PROMOTIONPLANID IN (1400000011,1400000020) AND c.CUSTOMERID=1300176188 AND d.CUSTOMERID=c.CUSTOMERID AND d.PROMOTIONPLANID=a.PROMOTIONPLANID
