
--Purge for CRM_CUSTOMERS_SERVICES_UPDATE_LifecycleLOG
SET NOCOUNT ON ;

WHILE 1 = 1
BEGIN
MERGE INTO CRM25_CUSTOMER..CRM_CUSTOMERS_SERVICES_UPDATE_LifecycleLOG WITH (ROWLOCK) target
USING (
SELECT TOP 1000 id FROM  CRM25_CUSTOMER..CRM_CUSTOMERS_SERVICES_UPDATE_LifecycleLOG WITH (NOLOCK)
WHERE INSERTDATE<=DATEADD(MONTH,-1,GETDATE())
) source
ON ( source.id = target.id ) 
WHEN MATCHED THEN DELETE;
IF @@rowcount = 0 BREAK;
END

--Purge for CRM_CUSTOMERS_MAPPING_UPDATE_LifecycleLOG
SET NOCOUNT ON ;

WHILE 1 = 1
BEGIN
MERGE INTO CRM25_CUSTOMER..CRM_CUSTOMERS_MAPPING_UPDATE_LifecycleLOG WITH (ROWLOCK) target
USING (
SELECT TOP 1000 id FROM  CRM25_CUSTOMER..CRM_CUSTOMERS_MAPPING_UPDATE_LifecycleLOG WITH (NOLOCK)
WHERE INSERTDATE<=DATEADD(MONTH,-1,GETDATE())
) source
ON ( source.id = target.id ) 
WHEN MATCHED THEN DELETE;
IF @@rowcount = 0 BREAK;
END

