
/****** Object:  Table [dbo].[CRM_CUSTOMERS_LIQUIX_SUBSCRIPTIONS]    Script Date: 06/12/2010 15:50:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CRM_CUSTOMERS_LIQUIX_SUBSCRIPTIONS](
	[ID] [int] NOT NULL,
	[CUSTOMERID] [int] NOT NULL,
	[MSISDN] [varchar](25) NOT NULL,
	[PAYMENTTYPE] [int] NOT NULL,
	[BANKNAME] [nvarchar](100) NULL,
	[BANKNUMBER] [nvarchar](50) NULL,
	[MINIMUMAMOUNT] [decimal](18, 4) NULL,
	[RECURRINGDATE] [datetime] NULL,
	[TOPUPAMOUNT] [decimal](18, 4) NULL,
	[REFERENCECODE] [nvarchar](50) NULL,
	[COMMENTS] [nvarchar](100) NULL,
	[SUBSCRIBEDATE] [datetime] NOT NULL,
	[ENABLED] [bit] NOT NULL,
 CONSTRAINT [PK_CRM_CUSTOMERS_LIQUIX_SUBSCRIPTIONS] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [CRM_CUSTOMERS_LIQUIX_SUBSCRIPTIONS_CUSTOMERID_PAYMENTTYPE] UNIQUE NONCLUSTERED 
(
	[CUSTOMERID] ASC,
	[PAYMENTTYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE CLUSTERED INDEX CRM_CUSTOMERS_LIQUIX_SUBSCRIPTIONS_MSISDN ON  CRM_CUSTOMERS_LIQUIX_SUBSCRIPTIONS(MSISDN)


SET ANSI_PADDING OFF
GO



