SP_HELP CRM_CUSTOMERS_SERVICES


--1.删除主键及索引
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CRM_CUSTOMERS_SERVICES]') AND name = N'PK_CRM_CUSTOMERS_SERVICES')
ALTER TABLE [dbo].[CRM_CUSTOMERS_SERVICES] DROP CONSTRAINT [PK_CRM_CUSTOMERS_SERVICES]
GO

--2.增加主键且非聚集

--创建简单索引

CREATE INDEX IX_ProductVendor_VendorID 
    ON Purchasing.ProductVendor (VendorID); 
    

ALTER TABLE CRM_CUSTOMERS_SERVICES WITH NOCHECK ADD
    CONSTRAINT [PK_CRM_CUSTOMERS_SERVICES] PRIMARY KEY  NONCLUSTERED
     (
          ENDDATE
     )
    GO

--3.创建聚集索引

CREATE CLUSTERED INDEX IC_CRM_CUSTOMERS_SERVICES ON CRM_CUSTOMERS_SERVICES (ENDDATE)
