

ALTER TABLE CRM_CUSTOMERS_SPECIFICNUMBER
DISABLE CHANGE_TRACKING;


IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CRM_CUSTOMERS_SPECIFICNUMBER]') AND name = N'PK_CRM_CUSTOMERS_SPECIFICNUMBE')
ALTER TABLE [dbo].CRM_CUSTOMERS_SPECIFICNUMBER DROP CONSTRAINT [PK_CRM_CUSTOMERS_SPECIFICNUMBE]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CRM_CUSTOMERS_SPECIFICNUMBER]') AND name = N'UN_CustomersSpecificNumberId')
ALTER TABLE [dbo].CRM_CUSTOMERS_SPECIFICNUMBER DROP CONSTRAINT [UN_CustomersSpecificNumberId]
GO

ALTER TABLE CRM_CUSTOMERS_SPECIFICNUMBER ADD CONSTRAINT CUSTOMERSPECIFICNUMBERID PRIMARY KEY NONCLUSTERED(CustomersSpecificNumberId)

ALTER TABLE CRM_CUSTOMERS_SPECIFICNUMBER
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON)


select * from SYS.change_tracking_databases
select OBJECT_NAME(object_id) from SYS.change_tracking_tables

ALTER TABLE	CRM_CUSTOMERS_RESOURCEMB	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_RATEPLAN	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_COIN_CRDB	DISABLE CHANGE_TRACKING;
ALTER TABLE	SYS_LANGUAGETYPE	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_CUSTOMERS_SERVICES	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_BUNDLE	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MVNO_VOICEMAIL_SETTING	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_ROAMING_ZONE	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_UNITCATEGORY	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_TRANSLATION	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_BLACKWHITELIST	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_BLACKWHITELIST_ITEM	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_PROMOTIONPLAN	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_RATEPLAN_BLACKWHITELIST	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_CUSTOMERS	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_DEALERS	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_CUSTOMERS_PROPERTY	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MOBILE_CALLFORWARD	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_SPECIFICNUMBER_GROUP	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MOBILE_CALLBARRING	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_ROAMING_ZONE_DETAILS	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_RATEPLAN_DETAILS	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MVNO_BRS_TAXCODE_POSTCODE	DISABLE CHANGE_TRACKING;
ALTER TABLE	RM_PROMOTIONPLAN_DETAIL	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MVNO_BRS_TAXCODE	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_CUSTOMERS_SPECIFICNUMBER	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MOBILE_NETWORK	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_MOBILE_MULTIPLEIMSI	DISABLE CHANGE_TRACKING;
ALTER TABLE	CRM_CUSTOMERS_PROMOTION	DISABLE CHANGE_TRACKING;