--1.删除主键及索引
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CRM_CUSTOMERS_EXTRAUSAGE]') AND name = N'PK__CRM_CUST__3214EC266B8FCA2D')
ALTER TABLE [dbo].[CRM_CUSTOMERS_EXTRAUSAGE] DROP CONSTRAINT [PK__CRM_CUST__3214EC266B8FCA2D]
GO

--2.增加主键且非聚集

--创建简单索引

CREATE INDEX IX_ProductVendor_VendorID 
    ON Purchasing.ProductVendor (VendorID); 
    

ALTER TABLE CRM_CUSTOMERS_EXTRAUSAGE ADD CONSTRAINT PK_CRM_CUSTOMERS_EXTRAUSAGE PRIMARY KEY NONCLUSTERED (ID)

--3.创建聚集索引

CREATE CLUSTERED INDEX I_CUSTOMERID ON CRM_CUSTOMERS_EXTRAUSAGE (CUSTOMERID)


