--增加唯一索引
ALTER TABLE [dbo].[CRM_BEN_SAP_ORDERS] ADD CONSTRAINT [CRM_BEN_SAP_ORDERS_PONUMBER] UNIQUE(PONUMBER)

--删除唯一索引
/****** Object:  Index [CRM_BEN_SAP_ORDERS_ID]    Script Date: 06/10/2010 16:13:59 ******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CRM_BEN_SAP_ORDERS]') AND name = N'CRM_BEN_SAP_ORDERS_ID')
ALTER TABLE [dbo].[CRM_BEN_SAP_ORDERS] DROP CONSTRAINT [CRM_BEN_SAP_ORDERS_ID]
GO


