

DECLARE @SID INT
DECLARE @DICID INT
DECLARE @PARENTID INT
DECLARE @MaxDictionaryType INT
SELECT @SID=ISNULL(MAX(ID),1000000000)+1 FROM SYS_DICTIONARY WHERE ID LIKE '100%'
SELECT @DICID=ISNULL(MAX(DICTIONARYID),1000000000)+1 FROM SYS_DICTIONARY WHERE DICTIONARYID LIKE '100%'
SET @PARENTID=@DICID
set @MaxDictionaryType =12301
--select MAX([DICTIONARYTYPE])+1 from SYS_DICTIONARY where DICTIONARYTYPE like '12%'
--Parent record
select @PARENTID=ID from [SYS_DICTIONARY] where [DICTIONARYTEXT]=N'DoubleTriplePromotionMethod'

--Sub record
SET @SID=@SID+1
SET @DICID=@DICID+1
INSERT [dbo].[SYS_DICTIONARY] ([ID], [DICTIONARYID], [PARENTID], [DICTIONARYTYPE], [DICTIONARYTEXT], [VALUESID], [LEVELID], [ITEM_POST], [TOOLTIPTEXT], [LINK], [DESCRIPTIONID], [UPDATE_USERID], [UPDATE_TIME], [CREATE_USERID], [CREATE_TIME], [STATEID]) 
VALUES (@SID, @DICID, @PARENTID, @MaxDictionaryType, N'Dayticket', N'16', 2, 0, N'Dayticket', N'', N'Dayticket', 14, GETDATE(), 14, GETDATE(), 1)
SET @SID=@SID+1
SET @DICID=@DICID+1
INSERT [dbo].[SYS_DICTIONARY] ([ID], [DICTIONARYID], [PARENTID], [DICTIONARYTYPE], [DICTIONARYTEXT], [VALUESID], [LEVELID], [ITEM_POST], [TOOLTIPTEXT], [LINK], [DESCRIPTIONID], [UPDATE_USERID], [UPDATE_TIME], [CREATE_USERID], [CREATE_TIME], [STATEID]) 
VALUES (@SID, @DICID, @PARENTID, @MaxDictionaryType, N'Monthticket', N'15', 2, 0, N'Monthticket', N'', N'Monthticket', 14, GETDATE(), 14, GETDATE(), 1)


