--Dealer
SELECT * FROM CRM_DEALERS where DEALERID IN (100000,140000,150000,160000,240000,280000,290000)
SELECT * FROM CRM_MVNO_PROPERTIES

DELETE FROM CRM_DEALERS WHERE STATE=2

SELECT * FROM CRM_DEALERS WHERE PARENTID=-1

Update CRM_DEALERS set DEALERNODE='CPS Test',DEALERID=570000 where DEALERID=140000

--DELETE FROM CRM_DEALERS where FISCALUNITID NOT IN (SELECT FISCALUNITID FROM CRM_DEALERS WHERE FISCALUNITID IN (SELECT DEALERID FROM CRM_DEALERS WHERE PARENTID=-1))

SELECT * FROM SYS_MULTILINGUAL WHERE DealerID=140000

SELECT DISTINCT DealerID FROM SYS_MULTILINGUAL WHERE DealerID=570000



--DELETE FROM CRM_DEALERS_ATTACHEMENTS WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
----update CRM_DEALERS_ATTACHEMENTS set DEALERID=280000 where DEALERID=440000
----update CRM_DEALERS_ATTACHEMENTS set DEALERID=290000 where DEALERID=450000
--DELETE FROM CRM_DEALERS_OBOPRS WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
----update CRM_DEALERS_OBOPRS set DEALERID=280000 where DEALERID=440000
----update CRM_DEALERS_OBOPRS set DEALERID=290000 where DEALERID=450000
--DELETE FROM CRM_MVNO_TOPUP_CONFIG WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
----update CRM_MVNO_TOPUP_CONFIG set DEALERID=280000 where DEALERID=440000
----update CRM_MVNO_TOPUP_CONFIG set DEALERID=290000 where DEALERID=450000
--DELETE FROM CRM_DEALERS_PROPERTIES WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
----update CRM_DEALERS_PROPERTIES set DEALERID=280000 where DEALERID=440000
----update CRM_DEALERS_PROPERTIES set DEALERID=290000 where DEALERID=450000
--DELETE FROM CRM_DEALERS_LOYALTY_POINT WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
----update CRM_DEALERS_LOYALTY_POINT set DEALERID=280000 where DEALERID=440000
----update CRM_DEALERS_LOYALTY_POINT set DEALERID=290000 where DEALERID=450000
--DELETE FROM CRM_DEALERS_BANK WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
----update CRM_DEALERS_BANK set DEALERID=280000 where DEALERID=440000
----update CRM_DEALERS_BANK set DEALERID=290000 where DEALERID=450000
--DELETE FROM CRM_MVNO_PROPERTIES WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
--update CRM_MVNO_PROPERTIES set DEALERID=280000 where DEALERID=440000
--update CRM_MVNO_PROPERTIES set DEALERID=290000 where DEALERID=450000


--update CRM_DEALERS set DEALERID=280000 where DEALERID=440000
--update CRM_DEALERS set DEALERID=290000 where DEALERID=450000
--update CRM_DEALERS set DEALERNODE='2NR' WHERE DEALERID=240000
--update CRM_DEALERS set DEALERNODE='CPS' WHERE DEALERID=140000
--update CRM_DEALERS set DEALERNODE='PRS' WHERE DEALERID=290000

--Customers

--DELETE FROM CRM_CUSTOMERS_BANK
--DELETE FROM CRM_MVNO_CUSTOMERS_PROPERTY
--DELETE FROM CRM_CUSTOMERS_REMARKS
--DELETE FROM CRM_CUSTOMERS_PROPERTY
--DELETE FROM CRM_CUSTOMERS_PRODUCTS
--DELETE FROM CRM_CUSTOMERS_PRODUCTS_BAK
--DELETE FROM CRM_CUSTOMERS_PROMOTION
--DELETE FROM CRM_CUSTOMERS_PROMOTION_BAK
--DELETE FROM CRM_CUSTOMERS_SERVICES
--DELETE FROM CRM_DEFAULT_SERVICES
--DELETE FROM CRM_CUSTOMERS_RESOURCEMB
--DELETE FROM CRM_CUSTOMERS_RESOURCECS
--DELETE FROM CRM_CUSTOMERS_RESOURCETC
--DELETE FROM CRM_CUSTOMERS_MAPPING
--DELETE FROM CRM_CUSTOMERS
--DELETE FROM CRM_CUSTOMERS_FF
--DELETE FROM CRM_CUSTOMERS_FF_HISTORY
--DELETE FROM CRM_CUSTOMERS_FLEX2ND_NUMBER
--DELETE FROM CRM_CUSTOMERS_FLEX_RESTRICTION


--NPM
--DELETE FROM SYS_NPM_PROPERTY
--DELETE FROM SYS_NPM_DEALER
--DELETE FROM SYS_NPM_BATCH_INFO
--DELETE FROM SYS_NPM

--SIM
--DELETE FROM CRM_MOBILE_SIMCARDS_IMPORT_MASTER
--DELETE FROM CRM_MOBILE_SIMCARDS_IMPORT_LOG
--DELETE FROM CRM_MOBILE_SIMCARDS_IMPORT_DETAILS
--DELETE FROM CRM_MOBILE_SIMCARDS
--DELETE FROM CRM_MOBILE_SIMCARDS_ORDER
--DELETE FROM CRM_DEALERS_IMSI
--DELETE FROM CRM_DEALERS_ICCID
--DELETE FROM CRM_MOBILE_SIMCARD_PREACTIVATE_LOG



--Voucher card
--DELETE FROM CRM_DEALERS_VOUCHER
--DELETE FROM CRM_DEALERS_VOUCHER_BATCH_INFO



--TOP UP
--DELETE FROM CRM_MVNO_TOPUP_HISTORY_TPV
--DELETE FROM CRM_MVNO_TOPUP_HISTORY

--Trouble ticket
--DELETE FROM CRM_TT_HISTORY
--DELETE FROM CRM_TROUBLE_TICKET

--Lifecycle
--delete from CRM_LIFECYCLE_SMS_LOG
--delete from CRM_LIFECYCLE_EMAILS_ATTACHMENTS
--delete from CRM_LIFECYCLE_EMAILS
--delete from MVNO_FC_LIFECYCLE_LOG
--delete from CRM_LIFECYCLE_REPORTS
--delete from CRM_LIFECYCLE_RESOURCE_STATUSCHANGED_LOG

--Operation LOG
--delete from SYS25_LOG_OPERATION

----HLR
--select * from CRM_MOBILE_PROVISIONINGQUEUE

--DELETE FROM CRM_DEFAULT_PROVISION WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
--DELETE FROM dbo.CRM_DEFAULT_PROVISION_BAK WHERE PROVISIONID NOT IN (SELECT PROVISIONID FROM CRM_DEFAULT_PROVISION)
--DELETE FROM dbo.CRM_DEFAULT_PROVISION_CALLBARRING WHERE PROVISIONID NOT IN (SELECT PROVISIONID FROM CRM_DEFAULT_PROVISION)
--DELETE FROM dbo.CRM_DEFAULT_PROVISION_CALLFORWARD WHERE PROVISIONID NOT IN (SELECT PROVISIONID FROM CRM_DEFAULT_PROVISION)
--DELETE FROM dbo.CRM_DEFAULT_PROVISION_NETWORK WHERE PROVISIONID NOT IN (SELECT PROVISIONID FROM CRM_DEFAULT_PROVISION)

--DELETE FROM CRM_MOBILE_CALLBARRING
--DELETE FROM CRM_MOBILE_CALLBARRING_HISTORY
--DELETE FROM CRM_MOBILE_CALLFORWARD
--DELETE FROM CRM_MOBILE_CALLFORWARD_HISTORY
--DELETE FROM CRM_MOBILE_CALLWAITING
--DELETE FROM CRM_MOBILE_CALLWAITING_HISTORY
--DELETE FROM CRM_MOBILE_CAMELUCSI
--DELETE FROM CRM_MOBILE_CAMELUCSI_HISTORY
--DELETE FROM CRM_MOBILE_CUGFEATURE
--DELETE FROM CRM_MOBILE_CUGFEATURE_HISTORY
--DELETE FROM CRM_MOBILE_CUGSUBS
--DELETE FROM CRM_MOBILE_CUGSUBS_HISTORY
--DELETE FROM CRM_MOBILE_MULTIPLEIMSI
--DELETE FROM CRM_MOBILE_MULTIPLEIMSI_HISTORY
--DELETE FROM CRM_MOBILE_NETWORK
--DELETE FROM CRM_MOBILE_NETWORK_HISTORY
--DELETE FROM CRM_MOBILE_PROVISIONINGQUEUE
--DELETE FROM CRM_MOBILE_SS
--DELETE FROM CRM_MOBILE_SS_HISTORY
--DELETE FROM dbo.HLR_CallBarringOG_BSG
--DELETE FROM dbo.HLR_CallBarringSS
--DELETE FROM dbo.HLR_CallBarringSubsOption
--DELETE FROM dbo.HLR_CallForward
--DELETE FROM dbo.HLR_CallForwardBsg
--DELETE FROM dbo.HLR_CamelSubsInfo
--DELETE FROM dbo.HLR_CamelTdp
--DELETE FROM dbo.HLR_CugFeature
--DELETE FROM dbo.HLR_CugSubscription
--DELETE FROM dbo.HLR_GprsContext
--DELETE FROM dbo.HLR_MultiImsi
--DELETE FROM dbo.HLR_RECORD
--DELETE FROM dbo.HLR_RequestErrors
--DELETE FROM dbo.HLR_Sim
--DELETE FROM dbo.HLR_SSCallWaitActivStatus
--DELETE FROM dbo.HLR_SSProvisionStatus
--DELETE FROM dbo.HLR_SubscriberProfile
--DELETE FROM dbo.HlrCamelUCsi
--DELETE FROM dbo.HlrCamelUGCsi

--Billing


--SMS and EMAIL
--DELETE FROM CRM_MVNO_SMS_LOG

--Copy MVNO
--DELETE FROM CRM_Copy_MVNO_Detail
--DELETE FROM CRM_Copy_MVNO_IDMapping
--DELETE FROM CRM_Copy_MVNO_Info

--Rate plan

--select * from RM_DATECATEGORY
--DELETE FROM RM_DATECATEGORY
--select * from RM_TIMECATEGORY
--select * from RM_CALLDIRECTION
--DELETE FROM RM_CALLDIRECTION WHERE CALLDIRECTIONID>4000
--SELECT * FROM RM_CARRIER
--SELECT * FROM RM_COIN_REGULAR
--select * from RM_UNITCATEGORY
--DELETE FROM RM_UNITCATEGORY WHERE UNITCATEGORYID>4000
--select * from RM_ROAMING_OPERATORS_E164
--select * from RM_CALLTYPE
--select * from RM_INTERNATIONAL_ZONE
--  DELETE FROM RM_INTERNATIONAL_ZONE
--select * from RM_INTERNATIONAL_ZONE_DETAILS
--delete from RM_INTERNATIONAL_ZONE_DETAILS
--select * from RM_ROAMING_ZONE
--select * from RM_ROAMING_ZONE_DETAILS
--select * from RM_RATEPLAN_DETAILS
--select * from RM_TRANSLATION
--select * from RM_BUNDLE_PACKAGE
--select * From RM_RATEPLAN
--select * from RM_BUNDLE
--select * from RM_PACKAGE


--System
--select * FROM SYS_DICTIONARY

--SELECT * FROM SYS_MVNO_LANGUAGE
--SELECT * FROM SYS_MULTILINGUAL WHERE DEALERID=120000
--DELETE FROM SYS_MULTILINGUAL WHERE DEALERID NOT IN (SELECT DEALERID FROM CRM_DEALERS) AND DEALERID<>-1 AND DEALERID<>100000
--DELETE FROM SYS_MESSAGE_USER
--SELECT * FROM SYS_MESSAGE_USER
--DELETE FROM SYS_MESSAGE
--DELETE FROM SYS25_LOG_SECURITY
--DELETE FROM AuditLog
--DELETE FROM CRM_CONFIG_MVNOFORMNAME WHERE MVNOID NOT IN (SELECT DEALERID FROM CRM_DEALERS) AND MVNOID<>-1 AND MVNOID<>100000

--update SYS_MULTILINGUAL set DEALERID=280000 where DEALERID=440000
--update SYS_MULTILINGUAL set DEALERID=290000 where DEALERID=450000

--SELECT * FROM CRM_DEALERS

--SELECT * FROM SYS25_USER_ORG 
--SELECT * FROM SYS25_MODULE
--SELECT * FROM SYS25_USER
----DELETE FROM SYS25_USER WHERE DEPARTMENTID NOT IN (SELECT DISTINCT OrgID FROM SYS25_ORGANIZATION )
--SELECT * FROM SYS25_ROLE
--SELECT * FROM SYS25_USER_DEALER
--SELECT * FROM SYS25_USER_ROLE

--DELETE FROM SYS25_USER_ROLE
--DELETE FROM SYS25_USER_DEALER
--DELETE FROM SYS25_ROLE
--DELETE FROM SYS25_USER_ORG

--SELECT * FROM SYS25_ORGANIZATION WHERE ORGID=25
--DELETE FROM SYS25_ORGANIZATION WHERE MVNOID IS NULL 
--DELETE FROM SYS25_ORGANIZATION WHERE MVNOID NOT IN (SELECT DEALERID FROM CRM_DEALERS)
--update SYS25_ORGANIZATION set MVNOID=280000 where MVNOID=440000
--update SYS25_ORGANIZATION set MVNOID=290000 where MVNOID=450000

--SELECT * FROM SYS30_PERMISSION

--Drop table:

--DROP TABLE CRM_DEALERS_SETTINGS
--DROP TABLE CRM_DEALERS_1
--DROP TABLE CRM_DEALERS_20090902
--DROP TABLE CRM_DEALERS_UI 
--DROP TABLE dbo.ABC
--DROP TABLE dbo.ccr_bak
--DROP TABLE dbo.classTab
--DROP TABLE dbo.crm_customers_products_200902252103
--DROP TABLE dbo.network_bak
--DROP TABLE dbo.CRM_DEALERS_SETTINGS_1
--DROP TABLE dbo.CRM_DEALERS_SETTINGS_25022008
--DROP TABLE dbo.CRM_DEALERS_SETTINGS_BAK
--DROP TABLE dbo.Query
--DROP TABLE dbo.rd5555
--DROP TABLE dbo.rd9999
--DROP TABLE dbo.peter_coin
--DROP TABLE dbo.rm_calltype_20090104
--DROP TABLE dbo.rm_rateplan_details_1000001057
--DROP TABLE dbo.rm_rateplan_details_200903131107
--DROP TABLE dbo.rm_rateplan_details_200903141709
--DROP TABLE dbo.rm_rateplan_details_200903141728
--DROP TABLE dbo.rm_rateplan_details_20090327roamingbakup
--DROP TABLE dbo.rm_rateplan_details_200904032033_allbakup
--DROP TABLE dbo.rm_rateplan_details_orbitel_roaming_voice_200903162133
--DROP TABLE dbo.rm_roaming_zone_details_bak0528
--DROP TABLE dbo.rm_roaming_zone_details_tmp0528
--DROP TABLE dbo.rm_roaming_zone_details_tmp0528_ex2
--DROP TABLE dbo.rm_translation_200904032033_allbakup
--DROP TABLE dbo.rzdxxxxxx
--DROP TABLE dbo.Sheet1$
--DROP TABLE dbo.SPAIN
--DROP TABLE dbo.SQL_TEST
--DROP TABLE dbo.student
--DROP TABLE dbo.SYS_ID
--DROP TABLE dbo.SYS_LANGUAGE
--DROP TABLE dbo.sys_language_bak_20090216
--DROP TABLE dbo.sys_npm_20090423
--DROP TABLE dbo.SYS_NPM_20090713_TEM
--DROP TABLE dbo.sys_npm_bright
--DROP TABLE dbo.SYS_NPM_DEALER_1
--DROP TABLE dbo.sys_npm_dealer_20090423
--DROP TABLE dbo.SYS_NPM_DEALER_20090713_TEM
--DROP TABLE dbo.sys_npm_dealer_bright
--DROP TABLE dbo.SYS_TRANSLATION_20090304
--DROP TABLE dbo.sys_translation_new
--DROP TABLE dbo.SYS_TRANSLATION1
--DROP TABLE dbo.tblBatches
--DROP TABLE dbo.tblBatchPartialAggs
--DROP TABLE dbo.tblConnections
--DROP TABLE dbo.tblInterestingEvents
--DROP TABLE dbo.tblMiscInfo
--DROP TABLE dbo.tblPlanRows
--DROP TABLE dbo.tblPlans
--DROP TABLE dbo.tblProcedureNames
--DROP TABLE dbo.tblStatements
--DROP TABLE dbo.tblStmtPartialAggs
--DROP TABLE dbo.tblTimeIntervals
----DROP TABLE dbo.tblTimeIntervals
--DROP TABLE dbo.tblTracedEvents
--DROP TABLE dbo.tblTraceFiles
--DROP TABLE dbo.tblUniqueBatches
--DROP TABLE dbo.tblUniquePlanRows
--DROP TABLE dbo.tblUniquePlans
--DROP TABLE dbo.tblUniqueStatements
--DROP TABLE dbo.tblWarnings
--DROP TABLE dbo.temp_npm
--DROP TABLE dbo.temp_trc
--DROP TABLE dbo.temp_trc1
--DROP TABLE dbo.temp_trc2
--DROP TABLE dbo.test
--DROP TABLE dbo.TEST_PAGE_TABLE
--DROP TABLE dbo.testtable
--DROP TABLE dbo.tmp_CRM_MOBILE_SIMCARDS
--DROP TABLE dbo.TMP_CUSTOMERS_SERVICES_CHECK_20090312
--DROP TABLE dbo.TMP_RATEPLANDETAILS_IMPORT
--DROP TABLE dbo.TMP001_RELATIONS
--DROP TABLE dbo.TraceTable
--DROP TABLE dbo.TraceTable_Chris
--DROP TABLE dbo.translog
--DROP TABLE SYS25_ROLE_PERMISSION
--DROP TABLE SYS_MVNO_LANGUAGE
--DROP TABLE CRM_CUSTOMERS_MAPPING_1
--DROP TABLE CRM_CUSTOMERS_PRODUCTS_1
--DROP TABLE CRM_CUSTOMERS_SERVICES_1
--DROP TABLE crm_customers_services_20090228
--DROP TABLE crm_customers_services_20090228duplicatebundle
--DROP TABLE crm_customers_services_200903121635
--DROP TABLE crm_customers_services_ryan_20090213
----DROP TABLE CRM_DEALERS_110000_ALTER_DEALERID_BAK
----DROP TABLE CRM_DEALERS_210000_ALTER_DEALERID_BAK
----DROP TABLE CRM_DEALERS_250000_ALTER_DEALERID_BAK
--DROP TABLE crm_dealers_cleanup_bob_11_24
--DROP TABLE CRM_DEALERS_SETTINGS_nouse
--DROP TABLE CRM_DEALERS_SETTINGS_nouse_BOB
--DROP TABLE CRM_DEALERS_VOUCHER_20090901
--DROP TABLE CRM_WHOLESALEBILL_OUTPUTFIELD11
--DROP TABLE crm_lifecycle_settings_bak_20090813
--DROP TABLE crm_lifecycle_settings_bak_20090814
--DROP TABLE dbo.ID_TABLE
--DROP TABLE dbo.CRM_MVNO_SEQUENCE
--DROP TABLE dbo.CRM_CUSTOMERS_RESOURCEMB_clean_0904
--DROP TABLE dbo.CRM_CUSTOMERS_RESOURCEMB_TEST_090906
--DROP TABLE dbo.CRM_LIFECYCLE_DISALLOWED_TRAFFICS_200902241025
--DROP TABLE dbo.CRM_LIFECYCLE_DISALLOWED_TRAFFICS_200903011152
--DROP TABLE dbo.CRM_LIFECYCLE_FREEPHONES_200902241025
--DROP TABLE dbo.CRM_LIFECYCLE_SETTINGS_DETAILS_bak_20090813
--DROP TABLE dbo.CRM_LIFECYCLE_SETTINGS_DETAILS_bak_20090814
--DROP TABLE dbo.CRM_LIFECYCLE_SMS_TEMPLET_bak_20090813
--DROP TABLE dbo.crm_mnp_npdb_esvf_200902021436
--DROP TABLE dbo.crm_mnp_npdb_esvf_20090202x
--DROP TABLE dbo.crm_mnp_npdb_esvf_20090604
--DROP TABLE dbo.crm_mnp_npdb_esvf_bak20090531
--DROP TABLE dbo.CRM_TT_USER_200903052239
--DROP TABLE dbo.FGNTP_32FILT_BAK20090531
--DROP TABLE dbo.RM_ROAMING_OPERATORS_E164_BACKUP_090819
--DROP TABLE dbo.SYS_MULTILINGUAL_1209_bob
--DROP TABLE dbo.SYS_MULTILINGUAL_1210_bob
--DROP TABLE dbo.SYS_MULTILINGUAL_1215_bob
--DROP TABLE dbo.SYS_MULTILINGUAL_1216_bob
--DROP TABLE dbo.SYS_MULTILINGUAL_1221_bob
--DROP TABLE dbo.SYS_MULTILINGUAL_CHRIS20091222
--DROP TABLE dbo.SYS_MULTILINGUAL_darren
--DROP TABLE dbo.SYS_MULTILINGUAL_darren_1223
--DROP TABLE dbo.SYS_MULTILINGUAL_Gary_20091222
--DROP TABLE dbo.SYS_MULTILINGUAL_Rabi
--DROP TABLE dbo.SYS_MULTILINGUAL_rabi_20091222
--DROP TABLE dbo.SYS_MULTILINGUAL_rabi2
--DROP TABLE dbo.SYS_MULTILINGUAL_rabi3_091225
--DROP TABLE dbo.SYS_MULTILINGUAL_Rabi4_091225
--DROP TABLE dbo.SYS25_MODULE_Rabi
--DROP TABLE dbo.SYS25_STYLE_Rabi_091225
--DROP TABLE dbo.SYS30_PERMISSION_Rabi
--DROP TABLE dbo.Test_Lincoln
--DROP TABLE dbo.Test_Lincoln_Detail
--DROP TABLE CRM_LIFECYCLE_REPORTS


--SYS-PREFIX TABLE
-- PROCEDURE
--FUNCTIOIN
--TRIGGER


select COUNT(1) from SYS30_PERMISSION
select * from SYS_MULTILINGUAL where DealerID=0
