

--2. check the status are correct in sys_npm_property, resourcemb, crm_mobile_simcards
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	--3576
	--AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	--所有三者不匹配的，排除899的情况，有2896
	
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=1
	--94
	
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=9
	--2
	
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=10
	--0
	
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=2
	--24
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=11
	--0
	
	SELECT A.RESOURCE,A.ICC,A.IMSI,A.CREATEDATE,A.STATUSID AS RESOURCESTATUSID,C.STATUSID AS NPMSTATUSID,D.STATUS AS ICCSTATUSID
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=3
	--2776

	--UPDATE SYS_NPM_PROPERTY SET STATUSID  = 1 WHERE RESOURCE = '34603040000'
	--UPDATE CRM_MOBILE_SIMCARDS SET STATUS = 1 WHERE ICCID  = '893457063100000160'

--2.1. NPM
	--npm is used, but not in resourcemb table
	SELECT A.Resource,A.StatusID FROM SYS_NPM_PROPERTY A, SYS_NPM_DEALER B
	WHERE A.Resource = B.Resource
	--AND B.DEALERID LIKE '50%'
	AND A.StatusID <> 8
	AND A.Resource NOT IN
	(SELECT Resource FROM CRM_CUSTOMERS_RESOURCEMB WHERE StatusID <> 20)
	--AND A.Resource IN
	--(SELECT CONVERT(VARCHAR(20),CAST(MSISDN AS BIGINT) + 34) FROM CRM_BT_MIGRATION_DATA_sam)
	ORDER BY A.RESOURCE
			
		--UPDATE SYS_NPM_PROPERTY
		--SET STATUSID = 8 WHERE RESOURCE IN
		--(
		--	SELECT A.Resource FROM SYS_NPM_PROPERTY A, SYS_NPM_DEALER B
		--	WHERE A.Resource = B.Resource
		--	AND B.DEALERID LIKE '50%'
		--	AND A.StatusID = 9 
		--	AND A.Resource NOT IN
		--	(SELECT Resource FROM CRM_CUSTOMERS_RESOURCEMB WHERE StatusID <> 20)
		--	AND A.Resource IN
		--	(SELECT CONVERT(VARCHAR(20),CAST(MSISDN AS BIGINT) + 34) FROM CRM_BT_MIGRATION_DATA_sam)
		--	--ORDER BY A.RESOURCE
		--)


--2.2. CRM_MOBILE_SIMCARDS
	--CRM_MOBILE_SIMCARDS is used, but not in resourcemb table
	SELECT A.ICCID,A.Status FROM CRM_MOBILE_SIMCARDS A 
	WHERE A.DEALERID LIKE '50%'
	AND A.Status <> 8
	AND A.ICCID NOT IN
	(SELECT ICCID FROM CRM_CUSTOMERS_RESOURCEMB WHERE StatusID <> 20)
	ORDER BY A.ICCID
			
	--UPDATE CRM_MOBILE_SIMCARDS
	--SET Status = 8 WHERE ICCID IN
	--(
	--	SELECT A.ICCID,A.Status FROM CRM_MOBILE_SIMCARDS A 
	--	WHERE A.DEALERID LIKE '50%'
	--	AND A.Status <> 8
	--	AND A.ICCID NOT IN
	--	(SELECT ICCID FROM CRM_CUSTOMERS_RESOURCEMB WHERE StatusID <> 20)
	--)
