31632235596	893105071000000559
31632000575	893105071000000575

select statusid,* from crm_customers_resourcemb where resource='31632235596' AND STATUSID<>20
select status,* from crm_mobile_simcards where ICCID='893105071000000559'
select statusid,* from sys_npm_property where resource='31632235596'



select statusid,* from crm_customers_resourcemb where resource='31632000575'  AND STATUSID<>20
select status,* from crm_mobile_simcards where ICCID='893105071000000575'
select statusid,* from sys_npm_property where resource='31632000575'

Active-1	94
Installed-9	2
Inactive-10	0
Deactive-2	24
Frozen-11	0




exec USPOUTPUT_CORRECTNPMSIMSTATUS_Chris 1
exec USPOUTPUT_CORRECTNPMSIMSTATUS_Chris 2

ALTER PROC USPOUTPUT_CORRECTNPMSIMSTATUS_Chris(@STATUS INT) AS

BEGIN
	
DECLARE @ICC VARCHAR(25)
DECLARE @RESOURCE VARCHAR(25)

--Backup data
--select * into SYS_NPM_PROPERTY_Chris_forCorrectStatus from SYS_NPM_PROPERTY where 1<>1
--select * into CRM_MOBILE_SIMCARDS_Chris_forCorrectStatus from CRM_MOBILE_SIMCARDS where 1<>1

DECLARE RESOURCE_CUR CURSOR FOR SELECT DISTINCT A.RESOURCE,A.ICC
	FROM CRM_CUSTOMERS_RESOURCEMB A, CRM_CUSTOMERS B, SYS_NPM_PROPERTY C, CRM_MOBILE_SIMCARDS D
	WHERE A.RESOURCE = C.RESOURCE
	AND A.ICC = D.ICCID
	AND A.CUSTOMERID = B.CUSTOMERID
	--AND B.DEALERID LIKE '50%'
	AND A.STATUSID <> 20
	AND (A.STATUSID <> C.StatusID OR A.STATUSID <> D.STATUS OR C.STATUSID <> D.STATUS)
	AND (A.STATUSID<>8 AND C.StatusID<>9 AND D.STATUS<>9)
	AND A.STATUSID=@STATUS
	
OPEN RESOURCE_CUR
FETCH NEXT FROM RESOURCE_CUR INTO @RESOURCE,@ICC
	WHILE @@FETCH_STATUS=0
		BEGIN
		    
	        --SELECT TOP 1 * FROM CRM_MOBILE_SIMCARDS
	        INSERT INTO SYS_NPM_PROPERTY_Chris_forCorrectStatus SELECT * FROM SYS_NPM_PROPERTY WHERE Resource=@RESOURCE
			UPDATE SYS_NPM_PROPERTY SET STATUSID=@STATUS,UpdateDate=GETDATE(),UpdateUserID=14 WHERE Resource=@RESOURCE
			INSERT INTO CRM_MOBILE_SIMCARDS_Chris_forCorrectStatus SELECT * FROM CRM_MOBILE_SIMCARDS WHERE ICCID=@ICC
			UPDATE CRM_MOBILE_SIMCARDS SET STATUS=@STATUS,CHANGESTATUSDATE=GETDATE() WHERE ICCID=@ICC
			
     	    FETCH NEXT FROM RESOURCE_CUR INTO @RESOURCE,@ICC
		END
DEALLOCATE RESOURCE_CUR
END


CHANGESTATUSDATE
2011-04-03 02:48:07.000

--select * from SYS_NPM_PROPERTY_Chris_forCorrectStatus from SYS_NPM_PROPERTY_Chris_forCorrectStatus where 1<>1
--select * from  CRM_MOBILE_SIMCARDS_Chris_forCorrectStatus from CRM_MOBILE_SIMCARDS where 1<>1

--npm is used, but not in resourcemb table

SELECT A.StatusID,COUNT(0) as number FROM SYS_NPM_PROPERTY A, SYS_NPM_DEALER B
	WHERE A.Resource = B.Resource
	--AND B.DEALERID LIKE '50%'
	AND A.StatusID <> 8
	AND A.Resource NOT IN
	(SELECT Resource FROM CRM_CUSTOMERS_RESOURCEMB WHERE StatusID <> 20)
	--AND A.Resource IN
	--(SELECT CONVERT(VARCHAR(20),CAST(MSISDN AS BIGINT) + 34) FROM CRM_BT_MIGRATION_DATA_sam)
    GROUP BY A.StatusID
	--ORDER BY A.RESOURCE
	
	SELECT A.ICCID,A.Status FROM CRM_MOBILE_SIMCARDS A 
	WHERE 
	--A.DEALERID LIKE '50%'
	A.Status <> 8
	AND A.ICCID NOT IN
	(SELECT ICCID FROM CRM_CUSTOMERS_RESOURCEMB WHERE StatusID <> 20)
	ORDER BY A.ICCID