DECLARE @CURRENTDATE1 DATETIME2
DECLARE @CURRENTDATE2 DATETIME2
SET @CURRENTDATE1=GETDATE()

SET @CURRENTDATE2=GETDATE()

SELECT DATEDIFF(MS,@CURRENTDATE1,@CURRENTDATE2)

SELECT @@ROWCOUNT

--Running at 23.51 QA DB:

--Spend about: 777 ms
--Effected ROWS: 126
