-- ================================================
-- Template generated from Template Explorer using:
-- Create Trigger (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- See additional Create Trigger templates for more
-- examples of different Trigger statements.
--
-- This block of comments will not be included in
-- the definition of the function.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER TRIGGER dbo.UTR_UPDATE_RESOURCE_STATUS
   ON  SYS_NPM_PROPERTY 
   AFTER INSERT,UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for trigger here
    DECLARE @RESOURCE VARCHAR(25)
    DECLARE @RESOURCE1 VARCHAR(25)
    DECLARE @RESOURCE2 VARCHAR(25)
    DECLARE @STARUSID INT
    DECLARE @DEALERID INT
    
    SELECT @RESOURCE=RESOURCE,@STARUSID=STATUSID FROM INSERTED
    SET @RESOURCE1=SUBSTRING(@RESOURCE,1,7)
    SET @RESOURCE2=SUBSTRING(@RESOURCE,1,6)
    SET @DEALERID=(SELECT TOP 1 DEALERID FROM SYS_NPM_DEALER WHERE RESOURCE=@RESOURCE)
    
    IF @RESOURCE1='3460304' AND @STARUSID=8 AND SUBSTRING(CONVERT(VARCHAR(10),@DEALERID),1,2)='50'
		BEGIN 
			UPDATE SYS_NPM_PROPERTY SET STATUSID=5 WHERE RESOURCE=@RESOURCE
		END
	ELSE IF @RESOURCE2='346344' AND @STARUSID=8 AND @DEALERID=210000
		BEGIN
			UPDATE SYS_NPM_PROPERTY SET STATUSID=6 WHERE RESOURCE=@RESOURCE
		END

END
GO

/*
SELECT TOP 10 RESOURCE,SUBSTRING(RESOURCE,1,7),SUBSTRING(RESOURCE,1,6) FROM CRM_CUSTOMERS_RESOURCEMB WHERE RESOURCE LIKE '34%'
SELECT TOP 10 SUBSTRING(CONVERT(VARCHAR(10),DEALERID),1,2),DEALERID FROM CRM_DEALERS WHERE DEALERID LIKE '50%'
*/

/*
--Test 1
INSERT INTO SYS_NPM_DEALER VALUES(
(SELECT ISNULL(MAX(ID),1000000000)+1 FROM SYS_NPM_DEALER WHERE ID LIKE '10%'),
'34634444008',210000,1)

INSERT INTO SYS_NPM_PROPERTY VALUES(
'34634444008',
NULL,
8,
NULL,
NULL,
NULL,
NULL,
NULL,
GETDATE(),
14,
GETDATE(),
14,
GETDATE(),
NULL)

UPDATE SYS_NPM_PROPERTY SET STATUSID=5 WHERE RESOURCE='34634444008'

SELECT *FROM SYS_NPM_PROPERTY WHERE RESOURCE='34634444008'
SELECT * FROM SYS_NPM_DEALER WHERE Resource='34634444008'
DELETE FROM SYS_NPM_PROPERTY WHERE RESOURCE='34634444008'
DELETE FROM SYS_NPM_DEALER WHERE Resource='34634444008'

--Test 2
INSERT INTO SYS_NPM_DEALER VALUES(
(SELECT ISNULL(MAX(ID),1000000000)+1 FROM SYS_NPM_DEALER WHERE ID LIKE '10%'),
'34603044008',210000,1)

INSERT INTO SYS_NPM_PROPERTY VALUES(
'34603044008',
NULL,
8,
NULL,
NULL,
NULL,
NULL,
NULL,
GETDATE(),
14,
GETDATE(),
14,
GETDATE(),
NULL)

UPDATE SYS_NPM_PROPERTY SET STATUSID=8 WHERE RESOURCE='34603044008'

SELECT *FROM SYS_NPM_PROPERTY WHERE RESOURCE='34603044008'
SELECT * FROM SYS_NPM_DEALER WHERE Resource='34603044008'
DELETE FROM SYS_NPM_PROPERTY WHERE RESOURCE='34603044008'
DELETE FROM SYS_NPM_DEALER WHERE Resource='34603044008'
*/